<?php

namespace ContainerCgTPgYS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdatePassewordFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\UpdatePassewordFormType' shared autowired service.
     *
     * @return \App\Form\UpdatePassewordFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/UpdatePassewordFormType.php';

        return $container->privates['App\\Form\\UpdatePassewordFormType'] = new \App\Form\UpdatePassewordFormType();
    }
}
