<?php

namespace ContainerRxXb0vA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Bwc2nIGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bwc2nIG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bwc2nIG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::EmailToUser' => ['privates', '.service_locator.rSeK3yh', 'get_ServiceLocator_RSeK3yhService', true],
            'App\\Controller\\AdminController::creatCategorie' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\AdminController::editCategorie' => ['privates', '.service_locator.moJP5c2', 'get_ServiceLocator_MoJP5c2Service', true],
            'App\\Controller\\AdminController::editUser' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\AdminController::eraseCategorie' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\AdminController::eraseUser' => ['privates', '.service_locator.rSeK3yh', 'get_ServiceLocator_RSeK3yhService', true],
            'App\\Controller\\AdminController::usersList' => ['privates', '.service_locator.QOjUGpS', 'get_ServiceLocator_QOjUGpSService', true],
            'App\\Controller\\RegistrationController::profilEmailUpdate' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\RegistrationController::profilPasswordUpdate' => ['privates', '.service_locator.GFm1rxI', 'get_ServiceLocator_GFm1rxIService', true],
            'App\\Controller\\RegistrationController::profilUpdate' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.Oi4_xhu', 'get_ServiceLocator_Oi4XhuService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AdminController:EmailToUser' => ['privates', '.service_locator.rSeK3yh', 'get_ServiceLocator_RSeK3yhService', true],
            'App\\Controller\\AdminController:creatCategorie' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\AdminController:editCategorie' => ['privates', '.service_locator.moJP5c2', 'get_ServiceLocator_MoJP5c2Service', true],
            'App\\Controller\\AdminController:editUser' => ['privates', '.service_locator.ch4Jgvl', 'get_ServiceLocator_Ch4JgvlService', true],
            'App\\Controller\\AdminController:eraseCategorie' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\AdminController:eraseUser' => ['privates', '.service_locator.rSeK3yh', 'get_ServiceLocator_RSeK3yhService', true],
            'App\\Controller\\AdminController:usersList' => ['privates', '.service_locator.QOjUGpS', 'get_ServiceLocator_QOjUGpSService', true],
            'App\\Controller\\RegistrationController:profilEmailUpdate' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\RegistrationController:profilPasswordUpdate' => ['privates', '.service_locator.GFm1rxI', 'get_ServiceLocator_GFm1rxIService', true],
            'App\\Controller\\RegistrationController:profilUpdate' => ['privates', '.service_locator.oiABibH', 'get_ServiceLocator_OiABibHService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.Oi4_xhu', 'get_ServiceLocator_Oi4XhuService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AdminController::EmailToUser' => '?',
            'App\\Controller\\AdminController::creatCategorie' => '?',
            'App\\Controller\\AdminController::editCategorie' => '?',
            'App\\Controller\\AdminController::editUser' => '?',
            'App\\Controller\\AdminController::eraseCategorie' => '?',
            'App\\Controller\\AdminController::eraseUser' => '?',
            'App\\Controller\\AdminController::usersList' => '?',
            'App\\Controller\\RegistrationController::profilEmailUpdate' => '?',
            'App\\Controller\\RegistrationController::profilPasswordUpdate' => '?',
            'App\\Controller\\RegistrationController::profilUpdate' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::registration' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminController:EmailToUser' => '?',
            'App\\Controller\\AdminController:creatCategorie' => '?',
            'App\\Controller\\AdminController:editCategorie' => '?',
            'App\\Controller\\AdminController:editUser' => '?',
            'App\\Controller\\AdminController:eraseCategorie' => '?',
            'App\\Controller\\AdminController:eraseUser' => '?',
            'App\\Controller\\AdminController:usersList' => '?',
            'App\\Controller\\RegistrationController:profilEmailUpdate' => '?',
            'App\\Controller\\RegistrationController:profilPasswordUpdate' => '?',
            'App\\Controller\\RegistrationController:profilUpdate' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:registration' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
